(function _Util_s_() {

'use strict';

let _ = _global_.wTools;
let Parent = null;
let Self = _.Matrix;

// --
// borrow
// --

/**
 * The method is a temporary cache for matrix,
 * writes the matrix to a specific object depending on the index.
 * Depends on index and key that is generated by bufferConstruction name and dimensions of matrix.
 *
 * @example
 * var buffer = new I32x( 6 )
 *
 * var m = new _.Matrix
 * ({
 *   buffer,
 *   dims : [ 3, 3 ],
 *   inputTransposing : 1,
 * });
 *
 * var got = matrix._TempBorrow( m, [ 4, 4 ], 1 );
 * console.log( got );
 * // log
 * new I32x
 * [
 *  0, 0, 0, 0,
 *  0, 0, 0, 0,
 *  0, 0, 0, 0,
 * ];
 *
 * @param { Matrix } Matrix - an instance of matrix.
 * @param { Array } dims - size of provided matrix.
 * @param { Number } index - Number of method, which will be called.
 * @returns { Matrix } - Returns instance of Matrix based on provided arguments.
 * @method _TempBorrow
 * @throws { Error } If (arguments.length) is not 3.
 * @throws { Error } If {-src-} is not instance of Matrix.
 * @throws { Error } If {-dims-} is not array.
 * @class Matrix
 * @namespace wTools
 * @module Tools/math/Matrix
 */

function _TempBorrow( src, dims, index )
{
  let bufferConstructor;

  _.assert( arguments.length === 3, 'Expects exactly three arguments' );
  _.assert( src instanceof Self || src === null );
  _.assert( _.arrayIs( dims ) || dims instanceof Self || dims === null );

  if( !src )
  {

    bufferConstructor = this.long.longDescriptor.type;
    if( !dims )
    dims = src;

  }
  else
  {

    if( src.buffer )
    bufferConstructor = src.buffer.constructor;

    if( !dims )
    if( src.dims )
    dims = src.dims.slice();

  }

  if( dims instanceof Self )
  dims = dims.dims;

  _.assert( _.routineIs( bufferConstructor ) );
  _.assert( _.arrayIs( dims ) );
  _.assert( index <= 3 );
  _.assert( !!this._TempMatrices[ index ] );

  let key = bufferConstructor.name + '_' + dims.join( 'x' );

  if( this._TempMatrices[ index ][ key ] )
  return this._TempMatrices[ index ][ key ];

  let result = this._TempMatrices[ index ][ key ] = new Self
  ({
    dims,
    buffer : new bufferConstructor( this.ScalarsPerMatrixForDimensions( dims ) ),
    inputTransposing : 0,
  });

  return result;
}

//

/**
 * This is a specialized method for executing TempBorrow for passing [ 0 ] index.
 *
 * @param { Matrix } Matrix - an instance of matrix.
 * @returns { Matrix } - Returns instance of Matrix based on provided arguments.
 * @method TempBorrow1
 * @throws { Error } If (arguments.length) is more than 1.
 * @throws { Error } If {-src-} is not instance of Matrix.
 * @class Matrix
 * @namespace wTools
 * @module Tools/math/Matrix
 */

function TempBorrow0( src )
{
  _.assert( arguments.length === 1 );
  if( src instanceof Self )
  return Self._TempBorrow( src, src , 0 );
  else
  return Self._TempBorrow( null, src , 0 );
}

//

function tempBorrow0( src ) /* qqq : improve jsdoc */
{
  _.assert( arguments.length <= 1 );
  if( src === undefined )
  src = this;
  return Self._TempBorrow( this, src , 0 );
}

//

/**
 * This is a specialized method for executing TempBorrow for passing [ 1 ] index.
 *
 * @param { Matrix } Matrix - an instance of matrix.
 * @returns { Matrix } - Returns instance of Matrix based on provided arguments.
 * @method TempBorrow1
 * @throws { Error } If (arguments.length) is more than 1.
 * @throws { Error } If {-src-} is not instance of Matrix.
 * @class Matrix
 * @namespace wTools
 * @module Tools/math/Matrix
 */

function TempBorrow1( src )
{
  _.assert( arguments.length === 1 );
  if( src instanceof Self )
  return Self._TempBorrow( src, src , 1 );
  else
  return Self._TempBorrow( null, src , 1 );
}

//

function tempBorrow1( src ) /* qqq : improve jsdoc */
{
  _.assert( arguments.length <= 1 );
  if( src === undefined )
  src = this;
  return Self._TempBorrow( this, src , 1 );
}

//

/**
 * This is a specialized method for executing TempBorrow for passing [ 2 ] index.
 *
 * @param { Matrix } Matrix - an instance of matrix.
 * @returns { Matrix } - Returns instance of Matrix based on provided arguments.
 * @method TempBorrow1
 * @throws { Error } If (arguments.length) is more than 1.
 * @throws { Error } If {-src-} is not instance of Matrix.
 * @class Matrix
 * @namespace wTools
 * @module Tools/math/Matrix
 */

function TempBorrow2( src )
{
  _.assert( arguments.length === 1 );
  if( src instanceof Self )
  return Self._TempBorrow( src, src , 2 );
  else
  return Self._TempBorrow( null, src , 2 );
}

//

function tempBorrow2( src ) /* qqq : improve jsdoc */
{
  _.assert( arguments.length <= 1 );
  if( src === undefined )
  src = this;
  return Self._TempBorrow( this, src , 2 );
}

//

function TempBorrow3( src )
{
  _.assert( arguments.length === 1 );
  if( src instanceof Self )
  return Self._TempBorrow( src, src , 3 );
  else
  return Self._TempBorrow( null, src , 3 );
}

//

function tempBorrow3( src ) /* qqq : improve jsdoc */
{
  _.assert( arguments.length <= 1 );
  if( src === undefined )
  src = this;
  return Self._TempBorrow( this, src , 3 );
}

// --
// relations
// --

let Statics = /* qqq : split static routines. ask how */
{

  /* borrow */

  _TempBorrow,
  TempBorrow0,
  TempBorrow : TempBorrow1,
  TempBorrow1,
  TempBorrow2,
  TempBorrow3,

  /* var */

  _TempMatrices : [ Object.create( null ) , Object.create( null ) , Object.create( null ) , Object.create( null ) ],

}

// --
// declare
// --

let Extension =
{

  // borrow

  _TempBorrow,
  TempBorrow0,
  tempBorrow0,
  TempBorrow : TempBorrow1,
  tempBorrow : tempBorrow1,
  TempBorrow1,
  tempBorrow1,
  TempBorrow2,
  tempBorrow2,
  TempBorrow3,
  tempBorrow3,

  //

  Statics,

}

_.classExtend( Self, Extension );

})();
